import { RepoDetailType } from './types';

// export const repoDetailMock: RepoDetailType = {
//   _id: '99999',
//   title: 'web前端',
//   isPublic: true,
//   description: '前端学习与知识沉淀',
//   word_count: 7429,
//   update_time: '2024-06-01 12:00',
//   owner: 'owner',
//   avatar: ['https://avatars.githubusercontent.com/u/1024025?v=4'],
//   docs_list: [
//     { docs_id: '1', docs_name: '蓝桥杯刷题心得' },
//     { docs_id: '2', docs_name: '数组和对象常用方法' },
//     { docs_id: '3', docs_name: '节流和防抖' },
//     { docs_id: '4', docs_name: 'SEO优化' },
//     { docs_id: '5', docs_name: '路由模式' },
//     { docs_id: '6', docs_name: 'less' },
//     { docs_id: '7', docs_name: '好用的工具' },
//     { docs_id: '8', docs_name: 'CSS--浮动' },
//     { docs_id: '9', docs_name: 'CSS-盒子模型、圆角边框、盒子阴影' },
//     { docs_id: '10', docs_name: 'CSS-三大特性' },
//     { docs_id: '11', docs_name: 'CSS-复合选择器、元素显示模式、背景' },
//     { docs_id: '12', docs_name: 'CSS-基本选择器、字体/文本属性、引入方式' },
//     { docs_id: '13', docs_name: 'HTML标签' },
//   ],
//   collect: true,
//   file_desc_title: '欢迎来到知识库',
//   file_desc: '知识库就像书一样，让多篇文档结构化，方便知识的创作与沉淀',
// };
